package com.ewnbd.lifvesafer.commons.utils

object AppConstants {

    const val BASE_WEB_SOCKET = "wss://lifvesafer.com/tracking/session/consumer/?session_id="

    const val ITEM_PER_PAGE = 30
    const val SEARCH_MINIMUM_LIMIT = 2

    const val SPLASH_TIME_OUT: Long = 2000

    const val LOCATION_REFRESH_TIME = 10000
    const val LOCATION_REFRESH_DISTANCE = 5

    const val PAYMENT_COMPLETE_URL = "https://lifvesafer.com/api/pay_tab_return/"
}

object AlertType {
    const val ALERT_SPEED = "sl"
    const val ALERT_BATTERY = "bl"
    const val ALERT_SOS = "sos"
    const val ALERT_TRACKING = "tr"
}

object SelectedLanguage {
    const val LANGUAGE_ENGLISH = 1
    const val LOCALE_ENGLISH = "en"
    const val LANGUAGE_ARABIC = 2
    const val LOCALE_ARABIC = "ar"
}

object PrivacyAndTerms {
    const val PRIVACY = "<p><strong>LIFVESAFER - PRIVACY POLICY</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer Mobile Limited respects your privacy. LifveSafer Mobile Limited and its affiliates (&ldquo;LifveSafer&rdquo; or the &ldquo;Company&rdquo;) offer mapping, GPS navigation, community based services and Carpool services to users of&nbsp;</span><a href=\"https://www.waze.com/\"><span style=\"font-weight: 400;\">www.LifveSafer.com</span></a><span style=\"font-weight: 400;\">&nbsp;(the &ldquo;Website&rdquo;) and/or users of LifveSafer&rsquo;s mobile applications (the &ldquo;Application&rdquo;) (collectively referred to as the &ldquo;Services&rdquo;). When you use our services, you&rsquo;re trusting us with your information. We understand this is a big responsibility and work hard to protect your information and put you in control.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">This Privacy Policy is meant to help you understand what information we collect, why we collect it, and how you can update, manage, and delete your information. This Privacy Policy covers:</span></p>\n" +
            "<ul>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#user-accounts\"><span style=\"font-weight: 400;\">User Accounts &amp; Accessing the Services</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#information-that-is-being-collected\"><span style=\"font-weight: 400;\">Information that is being collected</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#why-waze-collects-data\"><span style=\"font-weight: 400;\">Why LifveSafer collects data</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#sharing-your-information\"><span style=\"font-weight: 400;\">Sharing your information</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#visibility\"><span style=\"font-weight: 400;\">Visibility</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#waze_carpool_profile\"><span style=\"font-weight: 400;\">LifveSafer Carpool Profile</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#integration-with-social-networks\"><span style=\"font-weight: 400;\">Integration with social networks</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#integration-with-other-third-party-services\"><span style=\"font-weight: 400;\">Integration with other third party services</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#controlling-your-personal-information\"><span style=\"font-weight: 400;\">Controlling your personal information</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#how-waze-retains-data-we-collect\"><span style=\"font-weight: 400;\">How LifveSafer retains data we collect</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#how-does-waze-use-aggregated-information\"><span style=\"font-weight: 400;\">How does LifveSafer use aggregated information</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#cookies\"><span style=\"font-weight: 400;\">Cookies</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#advertising-campaigns\"><span style=\"font-weight: 400;\">Advertising campaigns</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#information-security\"><span style=\"font-weight: 400;\">Information security</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#compliance-&amp;-cooperation-with-regulators\"><span style=\"font-weight: 400;\">Compliance &amp; cooperation with regulators</span></a></li>\n" +
            "<li style=\"font-weight: 400;\"><a href=\"https://www.waze.com/legal/privacy/#changes-to-this-privacy-policy\"><span style=\"font-weight: 400;\">Changes to this Privacy Policy</span></a></li>\n" +
            "</ul>\n" +
            "<p><span style=\"font-weight: 400;\">This Privacy Policy is incorporated as part of the&nbsp;</span><a href=\"https://www.waze.com/legal/tos\"><span style=\"font-weight: 400;\">LifveSafer Terms of Use</span></a><span style=\"font-weight: 400;\">&nbsp;and&nbsp;</span><a href=\"https://www.waze.com/carpool/legal/tos\"><span style=\"font-weight: 400;\">LifveSafer Carpool Terms of Use</span></a><span style=\"font-weight: 400;\">&nbsp;(the &ldquo;Terms of Use&rdquo; or the &ldquo;Terms&rdquo;).&nbsp;Your use of the Services is subject to the Terms of Use,&nbsp;</span><a href=\"https://www.waze.com/legal/copyright\"><span style=\"font-weight: 400;\">Copyright Policy</span></a><span style=\"font-weight: 400;\">&nbsp;and this Privacy Policy and indicates your consent to them.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">To use our Services you must be 16 years of age or older. If you are under 16, you may not download or use the Services.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">In this Privacy Policy, the term &ldquo;personal information&rdquo; means information which you provide to us which personally identifies you, such as your name, email address or billing information, and, in certain circumstances, your location and route information or other data which can be reasonably linked to such information by LifveSafer.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">You can adjust your&nbsp;Privacy Settings&nbsp;in the LifveSafer app and choose which personal information we may collect about you and how your information is used.</span></p>\n" +
            "<p><strong>Contact LifveSafer - Privacy concerns reports</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">If you have any questions about this Privacy Policy, or if you believe that your privacy has been compromised in the course of using the Services, please contact LifveSafer at:&nbsp;</span><a href=\"mailto:privacy@waze.com\"><span style=\"font-weight: 400;\">privacy@LifveSafer.com</span></a><span style=\"font-weight: 400;\">. You may send LifveSafer other requests, responses, questions and complaints by email at:&nbsp;</span><a href=\"mailto:support@waze.com\"><span style=\"font-weight: 400;\">support@LifveSafer.com</span></a><span style=\"font-weight: 400;\">.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">To protect LifveSafer, our users, the public and for Legal reasons</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">We may also use and process your information and content, using different technologies to the following purposes:</span></p>\n" +
            "<ul>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To enforce the Terms of Use or Privacy Policy;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To contact you when LifveSafer believes it to be necessary;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To comply with any applicable law and assist law enforcement agencies under any applicable law, when LifveSafer has a good faith belief that LifveSafer&rsquo;s cooperation with the law enforcement agencies is legally mandated or meets the applicable legal standards and procedures;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To detect abuse and illegal activity; to detect and prevent fraud, misappropriation, infringements, identity theft and other illegal activities and misuse of the Services;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To handle breakdowns and malfunctions;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To take any action in any case of dispute, or legal proceeding of any kind between you and the Services, or between you and other users or third parties with respect to, or in relation with the Services;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">For purposes provided under this Privacy Policy and Terms of Use;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To help improve the safety and reliability of our Services. This includes detecting, preventing, and responding to security risks, and technical issues that could harm LifveSafer, our users, or the public;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To create aggregated and/or anonymous data (where such data does not enable the identification of a specific user). See &ldquo;How does LifveSafer use aggregated information&rdquo;, below;</span></li>\n" +
            "</ul>\n" +
            "<p><span style=\"font-weight: 400;\">We&rsquo;ll ask for your consent before using your information for a purpose that isn&rsquo;t covered in this Privacy Policy.</span></p>\n" +
            "<p><strong>Sharing your information</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">Personal information that you share</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">The Services are based on a community of users publicly sharing information with LifveSafer and with other members of that community.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">In particular, users may choose to share personal information such as name, age, gender, picture, their location information, reports and other files. This information may be shared either directly to the Services and to all users, such as in the case of traffic reports, or just to your friends on LifveSafer. This information may also be shared via third party services (such as social networks) which interact with the Services upon such users&rsquo; choice. For more information about your Carpool profile (if you choose to set one), see section titled&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#waze_carpool_profile\"><span style=\"font-weight: 400;\">LifveSafer Carpool Profile</span></a><span style=\"font-weight: 400;\">&nbsp;below.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">You can decide whether or not to upload content to the Services. However any content that you choose to share and submit for posting is neither private nor confidential and you should expect that it may be made public and known to others.&nbsp;Information you choose to upload will be posted along with your user name and other information including personal information you attached to your publicly available user profile. For example, your reports (map and road updates, traffic congestion updates, road accidents, etc.) will be posted on the LifveSafer map along with your username. You should note that certain road incidents you report may include your driving path within the vicinity of those incidents. Therefore, you must exercise caution and common sense when submitting information. At the very least you should demonstrate the same degree of caution as when publishing personal information by means other than the Internet and cellular services.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">In any event (but except as detailed below with respect to information shared from your social network accounts according to your privacy settings for such social network accounts), your email address will not be visible to others through any reports or user posts that you share or upload.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">if you choose to either record your own voice onto the Service, or to use the voice command features, LifveSafer will collect the voice information related to such use, including voice files. If, after recording your own voice, you chose to share your voice recordings, other LifveSafer users and other people will be able to download and use your voice recordings. Once downloaded, LifveSafer may not have any control over the voice files, so you should only share content that you are comfortable being made public.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">We, at LifveSafer, take great measures to provide you with the best experience you can have while using the Services. However, LifveSafer has no control over the conduct of any user and disclaims all liability in this regard. Users are advised to carefully and thoroughly consider whether or not to make public or available any information and carefully examine all necessary details related to any communication with other users prior to any engagement or communication being made.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">Participating in any user&rsquo;s activities as a result, directly or indirectly, from using LifveSafer, is entirely at your own risk. LifveSafer is not a party to any agreement entered into between the users in any circumstances. The user has the sole and ultimate responsibility regarding compliance with all laws, regulations or any other duty. We do not accept any liability for any loss, damage, cost or expense that you may suffer or incur as a result of or in connection with your participation in any activity or event initiated, held or conducted by a user or a third party nor in connection to any agreement between the users or third parties, including any activity or event related in any way, directly or indirectly, the Services or the use thereof.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">When LifveSafer shares your information</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer does not sell, rent or lease your personal information to third parties.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer will not share your personal information with others, without your permission, except for the following purposes and to the extent necessary in LifveSafer&rsquo;s good-faith discretion:</span></p>\n" +
            "<ul>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">As necessary for the facilitation and operation of the Services. For example, making public road incidents you report and which are associated with your username and your location;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">If LifveSafer reasonably believes that you have breached the Terms of Use or is investigating potential breach of the Terms of Use, or believes that you abused your rights to use the Services, or performed any act or omission that LifveSafer reasonably believes to be violating any applicable law, rules, or regulations. LifveSafer may share your information in these cases, with law enforcement agencies and other competent authorities and with any third party as may be required to handle any result of your wrongdoing;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">If LifveSafer is required, or reasonably believes that it is required by law to share or disclose your information;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">In any case of dispute, or legal proceeding of any kind between you and LifveSafer, or between you and other users with respect to, or in relation with the Services;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">In any case where LifveSafer reasonably believes that sharing information is necessary to protect against harm to the rights, property or safety of LifveSafer, our users, or the public as required or permitted by law, including to prevent imminent physical damage or damage to property;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To detect, prevent, or otherwise address fraud, security, or technical issues;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">If LifveSafer organizes the operation of the Services within a different framework, or through another legal structure or entity, or if LifveSafer is acquired by, or merged into or with another entity, or if LifveSafer enters bankruptcy, provided however, that those entities agree to be bound by the provisions of this Privacy Policy, with respective changes taken into consideration;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To collect, store, hold and manage your personal information through cloud based or hosting services or a third party or a party affiliated or connected to LifveSafer, as reasonable for business purposes, which may be located in the European Union and the U.S.A., potentially countries outside of your jurisdiction;</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer may also share personal information with companies or organizations connected or affiliated with LifveSafer, such as subsidiaries, sister-companies and parent companies (i.e. entities that belong to the Google group of companies);</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We work with other Google&rsquo;s services (such as Google Display and Video 360) for advertising and ad measurement purposes. In order to help advertisers decide what ads to show on LifveSafer, Google, and websites &amp; apps that partner with Google, we may share information with these services, such as a unique identifier for advertising (i.e, Advertising ID available on Android mobile devices or similar technologies). You can learn more about how Google uses information from sites or apps that use its services and how you can control that in&nbsp;</span><a href=\"https://policies.google.com/technologies/partner-sites\"><span style=\"font-weight: 400;\">this</span></a><span style=\"font-weight: 400;\">&nbsp;page. For more information see section titled&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#advertising-campaigns\"><span style=\"font-weight: 400;\">&lsquo;Advertising campaigns&rsquo;</span></a><span style=\"font-weight: 400;\">&nbsp;under this Privacy Policy.</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We also work with selected advertising and measurement services which help us understand how our users interact with ads served in our platform and in order to provide marketing, advertising and measurement services for LifveSafer with respect to LifveSafer&rsquo;s own marketing efforts, by using and sharing devices&rsquo; identifiers (i.e, Advertising ID, cookies or similar technologies).</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Personal information may also be shared with LifveSafer&rsquo;s trusted partners and service providers to process it for us, based on our instructions and in compliance with this policy and any other appropriate confidentiality and security measures. For example, we use service providers to help us with customer services.</span></li>\n" +
            "</ul>\n" +
            "<p><span style=\"font-weight: 400;\">We may share information which does not personally identify you with third party transportation services. For example, to allow you to find a carpool rider on third party transportation services, such as Moovit, we may share a temporary unique identifier along with pick-up and drop-off points that are generated based on proximity to your intended travel itinerary, with those third party transportation services. You can review the list of the relevant third party transportation services to your area and change your preferences at any time via the in-app settings.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer Carpool partners with employers, organizations and governmental entities (&ldquo;LifveSafer Carpool Partners&rdquo;) in order to encourage the use of carpooling. If you have joined a Carpool group which is promoted by a partner or any other third party, your carpool profile (or other information you have chosen to share) may be visible to other members of the group, including representatives of the partner or third party who may also be part of the group.</span></p>\n" +
            "<p><strong>Visibility</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">Please note that your username and some other information will be visible to others. Note that your username will be included along with any information you submit for posting (such as traffic reports or chat messages). It will therefore be visible to others. Also - your friends on LifveSafer will see your name &amp; profile photo and any other information you chose to share with them.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">If you prefer to remain invisible on the LifveSafer map, you can set the LifveSafer Application not to show your location on the map. To do so you should go to the Privacy Settings and adjust accordingly by switching on to Invisible Mode. If on,&nbsp;some features may not be available. If you make this choice, while you will be &lsquo;invisible&rsquo; on the map to other users, your location and route information will continue to be collected by LifveSafer for the purposes listed in this Privacy Policy and your Carpool profile (if you choose to set one) may be visible to other LifveSafer&rsquo;s users.</span></p>\n" +
            "<p><strong>Integration with other third party services</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer may offer you the option to link LifveSafer to third party services that may be useful to you (like, Spotify). Where LifveSafer detects an integration may be available (either because a third party service attempts to link to LifveSafer, or LifveSafer detects an installed service on the device which has an integration option, or you request a particular integration), LifveSafer will ask for confirmation to connect the accounts. If you choose to connect the accounts, LifveSafer will ask for your permission to share data with the third party service. You should only agree to connect accounts if you are comfortable with the third party service receiving the data set out at the time of connecting the accounts and LifveSafer is not responsible for the third party service&rsquo;s use of data. You can disconnect LifveSafer and the third party service at any time and LifveSafer will cease sharing data with that service from the point of disconnection onwards.</span></p>\n" +
            "<p><strong>How LifveSafer retains data we collect</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">Some data you can delete whenever you like, some data is deleted automatically, and some data we retain for longer periods of time when necessary. This section describes why we hold onto different types of data for different periods of time.</span></p>\n" +
            "<ul>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Information retained until you remove it&nbsp;- such as your &ldquo;Home, &ldquo;work&rdquo;, favorites, email address and other account related information. We&rsquo;ll keep this data in your LifveSafer Account until you choose to remove it and/or update it.</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Data that expires after a specific period of time&nbsp;- in some cases, you don&rsquo;t need to actively delete your information as we set retention timeframes based on the reason for the data&rsquo;s collection. For example, if you choose to connect your calendar to your LifveSafer Account, we extract your calendar events for several days in advance and delete them after their occurrence. We may also take steps to anonymize certain data within set timeperiods.</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Information retained until your LifveSafer Account is deleted&nbsp;- we may keep some data for the life of your LifveSafer Account if it&rsquo;s useful for helping us understand how users interact with our features and how we can improve our services. For example, if you made an incident report, we will keep information about how many reports you have submitted, even after the event is removed. When you delete your LifveSafer Account, the information about how many reports you have submitted is also removed.</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Information retained for extended time periods for limited purposes&nbsp;- sometimes business and legal requirements oblige us to retain certain information, for specific purposes, for an extended period of time. For example, when LifveSafer processes a payment for you, we&rsquo;ll retain this data for longer periods of time as required for tax or accounting purposes. Reasons we might retain some data for extended periods of time include:</span></li>\n" +
            "<ul>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Security, fraud &amp; abuse prevention</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Financial record-keeping</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Complying with legal or regulatory requirements</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Ensuring the continuity of our services</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Direct communications with LifveSafer</span></li>\n" +
            "</ul>\n" +
            "</ul>\n" +
            "<p><strong>How does LifveSafer use aggregated information?</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer may use anonymous, statistical or aggregated information (including anonymous location information), in a form that does not enable the identification of a specific user, to properly operate the Services, to improve the quality of the Services, to enhance your experience, to create new services and features, including customized services, to change or cancel existing content or service, and for further internal, commercial and statistical purposes (including advertising).</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer may also use anonymous, statistical or aggregated information collected on the Services, in a form that does not enable the identification of a specific user, by posting, disseminating, transmitting or otherwise communicating or making available such information to users of the Services, to the Services&rsquo; providers, partners and any other third party. For example, GPS information that we receive from your mobile device may be provided to map editors in an aggregated and/or anonymous form to help improve the map and solve map problems, traffic data may be provided to cities, aggregated use of LifveSafer Carpool may be provided to Carpool Partners and aggregated ads analysis may be provided to advertisers.</span></p>\n" +
            "<p><strong>Cookies</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer may use cookies and similar technologies on the Services. Cookies are packets of information sent by the Website&rsquo;s servers to your web browser and then sent back by the browser each time it accesses the Website&rsquo;s servers.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer may use cookies for various purposes, such as to save you the need to re-enter your username and password each time you log in, to facilitate the use of the Website, to collect statistical information, to verify information, and to customize the Website to your personal preferences and for information security purposes.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">Some of the cookies may expire when the session ends and you exit your browser. Other cookies are saved on your computer&rsquo;s hard drive. If you wish to block the Website&rsquo;s cookies, then please use the help button in your browser and follow the necessary instructions. However, bear in mind that disabling cookies may complicate or even prevent your use of the Website, or certain features thereof.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">For more information visit our&nbsp;</span><a href=\"https://www.waze.com/legal/cookies\"><span style=\"font-weight: 400;\">Cookie Policy</span></a><span style=\"font-weight: 400;\">.</span></p>\n" +
            "<p><strong>Information security</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer considers information security to be a top priority. LifveSafer services are built with strong security features that continuously protect your information. LifveSafer implements systems, applications and procedures to secure your personal information, to minimize the risk of theft, damage, loss of information, or unauthorized access or use of information. For example, we review our information collection, storage, and processing practices, including physical security measures, to prevent unauthorized access to our systems. In addition, we restrict access to personal information to LifveSafer employees, contractors, and agents who need that information in order to process it. Anyone with this access is subject to strict contractual confidentiality obligations and may be disciplined or terminated if they fail to meet these obligations.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">The insights we gain from maintaining our services help us detect and automatically block security threats from ever reaching you.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">However, these measures are unable to provide absolute assurance. Therefore, although LifveSafer takes great efforts to protect your personal information, LifveSafer cannot guarantee and you cannot reasonably expect that LifveSafer&rsquo;s databases will be immune from any wrongdoings, malfunctions, unlawful interceptions or access, or other kinds of abuse and misuse.</span></p>\n" +
            "<p><strong>Compliance &amp; cooperation with regulators</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">We regularly review this Privacy Policy and make sure that we process your information in ways that comply with it.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">Data transfers</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">We store data on servers located around the world and your information may be processed on servers located outside of the country where you live. Data protection laws vary among countries, with some providing more protection than others. Regardless of where your information is processed, we apply the same protections described in this policy.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">When we receive formal written complaints, we respond by contacting the person who made the complaint. We work with the appropriate regulatory authorities, including local data protection authorities, to resolve any complaints regarding the transfer of your data that we cannot resolve with you directly.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">.</span></p>\n" +
            "<p><strong>Changes to this Privacy Policy</strong></p>\n" +
            "<p><span style=\"font-weight: 400;\">LifveSafer may from time to time change the terms of this Privacy Policy. Substantial changes will take effect 30 days after LifveSafer has posted a:</span></p>\n" +
            "<ul>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">System message to users notifying them of changes to the Privacy Policy; and</span></li>\n" +
            "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Notification on the Website&rsquo;s homepage or any other relevant web pages, explaining the changes to the Privacy Policy alongside a comparison of the &ldquo;old&rdquo; and &ldquo;new&rdquo; versions of the Privacy Policy.</span></li>\n" +
            "</ul>\n" +
            "<p><span style=\"font-weight: 400;\">Other changes will take effect 7 days after their initial posting on the Website. However, if LifveSafer amends this Privacy Policy to comply with legal requirements, the amendments will become effective immediately upon their initial posting, or as required.</span></p>\n" +
            "<p><span style=\"font-weight: 400;\">You agree to be bound by any of the changes made in the terms of this Privacy Policy. Continuing to use the Services will indicate your acceptance of the amended terms. If you do not agree with any of the amended terms, you must avoid any further use of the Services.</span></p>\n" +
            "<p><br /><br /></p>"

    const val TERMS =
        "<p><strong>LIFVESAFER &ndash; Terms and condition</strong></p>\n" +
                "<p><strong>User Accounts &amp; Accessing the Services</strong></p>\n" +
                "<p><span style=\"font-weight: 400;\">Please note that when you use our Services , LifveSafer will set up an account (the &ldquo;Account&rdquo; or &ldquo;LifveSafer Account&rdquo;). LifveSafer will collect and use your information, including meta-data (as described below), in accordance with this Privacy Policy. This is the case whether or not you choose to actively register your Account, for example, by adding your email address or logging with your Google Account . LifveSafer may allow you to use the Services whether or not you choose to register your Account. If you choose to use the LifveSafer Services without registering your account you may do so by skipping the registration process. If you do so:</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer will still link all of your information with the non-registered Account and a unique identifier generated by LifveSafer in accordance with this Privacy Policy. This helps us do things like find you the best route.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer may allow you to connect your non-registered account with other devices and browsers (for example by using a QR code) and, if you choose to do so, information collected from these devices and browsers will be linked to your non-registered account.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">With the exception described in the bullet below, and as explained in the section&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#visibility\"><span style=\"font-weight: 400;\">&ldquo;Visibility&rdquo;</span></a><span style=\"font-weight: 400;\">&nbsp;below, your Account and the information associated with your Account (including your unique identifier) will be visible only to LifveSafer; and</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">When using the Services, your approximate location and other information you may choose to contribute will be visible to other users associated with the general username &ldquo;LifveSaferr&rdquo;.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Note that in order to access certain features of the Services (for example map editing, LifveSafer Carpool, ranking, moods) you will need to register your account.</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">If you do register your Account:</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer will link all of your information with your registered Account. This includes information received from all devices and browsers which you have chosen to sign in ;</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">With the exception described in the bullet below and as explained in the section&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#visibility\"><span style=\"font-weight: 400;\">&ldquo;Visibility&rdquo;</span></a><span style=\"font-weight: 400;\">&nbsp;below, your Account and information associated with your Account will be visible only to LifveSafer; and</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">When using the Services, your approximate location and other information you may choose to contribute will be visible to other users associated with this Account.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer may also establish and require from time to time additional or different means of identification and authentication for logging in and accessing the Services or for accessing certain features or designated sections of the Services.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Your login details are your responsibility. You are fully accountable for any use or misuse of your Account and personal details as a result of conveying your login details to someone else. You must maintain your login details in absolute confidentiality and avoid disclosing them to others. If you set a password, make sure that you change your password frequently and at least once every six months.</span></li>\n" +
                "</ul>\n" +
                "<p><strong>Information that is being collected</strong></p>\n" +
                "<p><span style=\"font-weight: 400;\">We want you to understand the types of information we collect as you use our services</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">LifveSafer collects information to provide better services to all its users - from figuring out stuff like what&rsquo;s the best route, to more complex things like monitoring traffic so you know when to leave, and showing you relevant ads while using LifveSafer. The information LifveSafer collects, and how that information is used, depends on how you choose to use our services and how you manage your privacy controls.</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">Information you create or provide to us:</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Account Information:&nbsp;information required when setting up an Account, such as your name, email address or information required to create a Carpool profile (if you choose to do so). Bear in mind that false, incorrect, or out-dated information may impair LifveSafer&rsquo;s ability to provide you with the Services and to contact you when necessary. LifveSafer will explicitly indicate the fields for mandatory completion. If you do not enter the requisite data in these fields, you may not be able to register your Account or to be provided with certain features, such as LifveSafer Carpool (but you may still use our Services as explained in the above section &ldquo;User Accounts &amp; Accessing the Services&rdquo;); and/or</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Information that you choose to share with LifveSafer:&nbsp;information that you choose to share with LifveSafer, including a username you have chosen, reports associated with your username, phone number, &ldquo;home&rdquo; or &ldquo;work&rdquo;, other &ldquo;favorites&rdquo;, car&rsquo;s details, destinations you may travel to, search queries, calendar information (if you choose to activate and use certain Service features like time to leave reminders) and files you have uploaded to the service, including voice and audio files, if applicable. You can also choose to add payment information to your Account, if applicable, specifically for paid services (such as LifveSafer Carpool). Even if you aren&rsquo;t registered to a LifveSafer Account, you might choose to provide us with information.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Communication which you choose to conduct through the LifveSafer Services:&nbsp;if you choose to use LifveSafer to communicate with other LifveSafer users or third parties through the LifveSafer Services, such as chat messages or sending pinned locations on the LifveSafer platform. We may also collect information when you exchange communication with LifveSafer, for example, if you submit a request, contact LifveSafer&rsquo;s support team, or report a violation to the abuse team.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Information from your social networks which you choose to connect to your LifveSafer Account:&nbsp;you may choose to connect your LifveSafer Account to your social network account(s). If you choose to do so, you may choose to share with LifveSafer and/or other users information from your social network accounts, such as your Facebook profile photo or other personal information shared by you. For more information see&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#integration-with-social-networks\"><span style=\"font-weight: 400;\">Integration with social networks</span></a><span style=\"font-weight: 400;\">, below.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">&ldquo;Find friends feature&rdquo;:&nbsp;if you use the &ldquo;find friends&rdquo; feature, LifveSafer will collect:</span></li>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Periodically, LifveSafer will collect all of the phone numbers which are stored on your device&rsquo;s phone contacts book. With regards to the &ldquo;find friends&rdquo; feature we only collect numbers in a form which is anonymous to LifveSafer; This information will be used to help us find and create a list of other LifveSafer users who you may know and with whom you may wish to connect. Note that we will not collect names, addresses or other information from your device&rsquo;s phone contacts book, however some of this information may be saved locally on your device and may be used within searches for your friend&rsquo;s name or address within the Services. and/or</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Your phone number. Your phone number will be used to verify your account and as part of the &ldquo;find friends&rdquo; feature , if applicable, to help find and create a list of other LifveSafer users who you may know and with whom you may wish to connect.</span></li>\n" +
                "</ul>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">You may also provide additional information that will be used to personalize the Services and enhance your experience with the Services. For example, if you provide us with your &ldquo;home&rdquo; and &ldquo;work&rdquo; information, we may provide you with what we think is the preferred route between those locations.</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">Information we collect as you use our services</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">We collect information about your activity in the Services, which we use to provide you with the Services of LifveSafer, including features which are meant to personalize your experience. This includes things like finding you the preferred route and proposing favorites or destinations commonly traveled by you to streamline your search and travel and, if you use LifveSafer Carpool - to match you with other drivers or riders. The activity information we collect may include:</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Detailed location, travel and route information. Location and route information is collected for example in the form of GPS signals (combined with a time-stamp), IP address and other information from sensors and receivers on or around your device,on which the Application is installed and activated. This location and route information is saved to a route history of all of the journeys you have made while using the Application. The types of location data we collect depends in part on your device and account settings. For example, depending on your selected device settings and/or your account settings we may collect information about your location and travel (or lack thereof) also while you are not using the app, in order to be able to tell you when to leave for planned drives, notify you about bad traffic in your area, provide you parking assistance, analyze how effective our ads are and more;</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Terms or venues you searched;</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Your views and interactions with content and ads;</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Your voice and audio information when you use voice and audio features;</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Communication or other content you chose to share with any third party, including LifveSafer users through the Services;</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Your activity on third-party sites and apps that you chose to link to your LifveSafer account or that you interact with through the Service.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Your activity as a LifveSafer Carpool&rsquo;s rider or driver, such as users you interacted with and rating that you have received from other users.</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">Meta-data (information about your device, browser and app use):</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">LifveSafer collects information about the use of the Services and information from the device you have LifveSafer installed on or the browser from which you use our Services. For example:</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer may collect and record how often you use our Services and for how long, your device type, unique identifiers, operating system type &amp; version, battery usage, the third party web pages or applications you visit or use or interact with via the Application, information that you viewed on our Services, advertisements that are shown to you or that you view or click on, the fact that you used the Services to communicate with other users and the fact that you used third parties application/services via LifveSafer to communicate with third parties, and the duration of such communications, the Internet Protocol (IP) address and the name of the domain that serves you to access the Services, and the geographic location of the device that you are using to log in and use LifveSafer on.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">LifveSafer may also collect information about apps installed on your device that LifveSafer can link with - such as third party music or media audio service apps (e.g. Spotify).</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We also collect information about the interaction of your devices with our Services, including, crash reports, system activity, and the date, time, and referrer URL of your request.</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">Information we collect about you from our partners</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">We work with ad partners, including advertisers on our platform and entities that belong to the Google group of companies, in order to show you more relevant and useful ads based on your LifveSafer activity and information associated with your device&rsquo;s identifier (i.e, Advertising identifiers or similar technologies) shared with us by our ad partners. Your device&rsquo;s identifier can be managed in your device&rsquo;s settings (for more information: see&nbsp;</span><a href=\"https://support.apple.com/en-us/HT202074\"><span style=\"font-weight: 400;\">here</span></a><span style=\"font-weight: 400;\">&nbsp;and&nbsp;</span><a href=\"https://policies.google.com/technologies/ads\"><span style=\"font-weight: 400;\">here</span></a><span style=\"font-weight: 400;\">).</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">You can decide whether we&rsquo;ll show you personalized ads or not through your in-app&nbsp;Privacy Settings&ndash;&gt;Ads personalization. Note: turning Ads personalization off does not turn off ads - only their personalization. For more information see section titled&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#advertising-campaigns\"><span style=\"font-weight: 400;\">&lsquo;Advertising campaigns&rsquo;</span></a><span style=\"font-weight: 400;\">&nbsp;under this Privacy Policy.</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">We may also receive aggregated, non-personally identifiable information and analysis from third parties measurement services which help us understand how our users interact with our ads. We may also receive information from third party services about how LifveSafer&rsquo;s own marketing efforts performed on third party sites or platforms.</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">We use various technologies to collect and store information, including, cookies, Advertising ID available on Android mobile devices or similar technologies, local storage, browser web storage, application data caches, databases, and server logs.</span></p>\n" +
                "<p><strong>Why LifveSafer collects data</strong></p>\n" +
                "<p><span style=\"font-weight: 400;\">LifveSafer may use information collected from or provided by you for the following purposes:</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">Provide our services</span></p>\n" +
                "<p><span style=\"font-weight: 400;\">We use your information to deliver our services. For example:</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">(If you have opted in to the &ldquo;find friends&rdquo; feature), use your phone number and the phone numbers which are stored in your device&rsquo;s phone book to find and create a list of other LifveSafer users who you may know and with whom you may wish to connect.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To provide advertising services, including personalized ads, in accordance with the section titled&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#advertising-campaigns\"><span style=\"font-weight: 400;\">&lsquo;Advertising campaigns&rsquo;</span></a><span style=\"font-weight: 400;\">&nbsp;under this Privacy Policy.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">To share your submissions with other users of the Services and to facilitate communication between you, LifveSafer and other users.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">If you joined LifveSafer Carpool, use your information, such as home, work and schedule, to find you potential carpoolers for your ride;</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">Maintain &amp; improve our services</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We also use your information to ensure our services are working as intended, such as tracking outages or troubleshooting issues you report to us. And we use your information to improve the service or to develop new features or services. For example, LifveSafer may use your route information to improve the accuracy of its mapping and navigation data.</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">Provide personalized services, including content and ads</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We use the information we collect to operate the Services and to customize your experience with the Services. For example, LifveSafer may use your &ldquo;home&rdquo; and &ldquo;work&rdquo; and other &ldquo;favorites&rdquo; information (if you choose to provide such information) or route history to offer routes based on how you&rsquo;ve chosen to travel between favorite destinations in the past. Based on your past activity on the Services we may also suggest to you drive predictions and common destinations where you use the app to navigate to and personalize your ETA.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">If you have opted in to use LifveSafer Carpool, we use your information to match you with riders and/or drivers to help you find a ride.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We may also use the information to provide you with support and handle requests and complaints.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Depending on your settings, we may also show you personalized ads based on your interests and past activity. For more information see section titled&nbsp;</span><a href=\"https://www.waze.com/legal/privacy/#advertising-campaigns\"><span style=\"font-weight: 400;\">&lsquo;Advertising campaigns&rsquo;</span></a><span style=\"font-weight: 400;\">&nbsp;under this Privacy Policy.</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">Measure performance</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We use data for analytics and measurement to understand how our services are used. For example, we analyze data about your usage of the Services to do things like optimize product design. We also use the data we collected about the ads you view or interact with (e.g. click on) to help advertisers understand the performance of their ad campaigns and to provide them with aggregated reports. We may also use data to measure the usability and effectiveness of LifveSafer&rsquo;s own marketing efforts on third party sites or platforms.</span></li>\n" +
                "</ul>\n" +
                "<p><span style=\"font-weight: 400;\">Communicate with you</span></p>\n" +
                "<ul>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We also use your information to send you updates, notices, announcements, users&rsquo; requests and additional information related to the Services (including through push notifications, email address and SMS);</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">We may also use your information to conduct surveys and questionnaires; And if you contact LifveSafer we may keep a record of your request in order to help solve any issues you might be facing.</span></li>\n" +
                "<li style=\"font-weight: 400;\"><span style=\"font-weight: 400;\">Subject to your prior indication of consent (to the extent required under applicable law), we may also use the email address that you provided to send you promotional and/or marketing materials. At any time you may choose not to receive such materials by clicking on the &ldquo;Unsubscribe&rdquo; link in the email messages that we may send to you. In any case, LifveSafer will not share your contact details with any advertiser, unless explicitly permitted or required by law.</span></li>\n" +
                "</ul>\n" +
                "<p>&nbsp;</p>"
}